### ISSUE TITLE
Necronomicon Issue

### ISSUE THREAD

**Issue by Acetraineraidan6** [cybercat5555/Miskatonic-Mysteries-Fabric#27] opened 2021-06-13 00:20 UTC
So Im trying to start the mod and I began to mess with it in creative to get a feel for the mod but I can't get to the 2nd page of the introduction, what happens is I press next then it says saving world and crashes me back to the launcher (For reference I use the curseforge launcher)

**Comment by cybercat5555** [comment] 2021-06-13 00:22
This is caused by using too new a version of Patchouli with MM, which is currently built for the previous major version. Downgrade your Patchi, but this will be fixed in the next major release of MM.

**Closed by cybercat5555** 2021-06-13 00:22 UTC

**Comment by Acetraineraidan6** [comment] 2021-06-13 01:13
Oh thanks for the help Ill try this out
