### ISSUE TITLE
1.18.2 Game won't load

### ISSUE THREAD

**Issue by Gamerbolts** [cybercat5555/Miskatonic-Mysteries-Fabric#58] opened 2022-07-19 21:08 UTC
Hello! I am creating a rather large modpack and I saw your mod and thought it would be perfect since I have a lack of magical mods. I put the mods in my mods folder to test it, all dependencies are in there from other mods that needed them. I tried to run it and I would crash to desktop, no crash log but here is the [latest.log](https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/files/9144737/latest.log) Unsure if there is anything you can do but thought I would post it here just in case. Thank you!

**Comment by Aelpecyem** [comment] 2022-07-19 21:11
duplicate of #56, fixed. a new build will release shortly

**Comment by Gamerbolts** [comment] 2022-07-19 21:11
Thank you, I did not see another topic posted. I was checking all over :D I will await the update!

**Closed as completed** 2022-07-19 21:11 UTC
